services:

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:${DB_EXTERNAL_PORT}/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - mysql
    env_file:
      - ./.env

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: