spring:
  application:
    name: waggle

  config:
    import: optional:file:.env[.properties]

#  datasource:
#    url: jdbc:mysql://localhost:${DB_EXTERNAL_PORT}/${DB_DATABASE}
#    username: root
#    password: ${DB_ROOT_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_SECRET_KEY}
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email

        provider:
            kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize
                token-uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user-name-attribute: id
                jwk-set-uri: https://kapi.kakao.com/v1/user/keys